version: '2.1'
services:

  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db_blog22
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - '8083:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend-spring-boot-app:
    container_name: backend-spring-boot-app
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend-spring-boot-app:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=db_blog22
      - DATABASE_PORT=3306